### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by MeikelLP** [snow-orld/opendrive#1]
Hey I'd like to use this project but I'm not sure under which license this project is/was released.

Could you please add a LICENSE file?

**Comment by snow-orld** [comment]
Sorry for reaching back this late. I have added a LICENSE file in this repository. Hope it helps.

**Comment by MeikelLP** [comment]
Thank you for providing a license with this much flexibility 👍 

Although I must say that this comes a little too late... I already implemented my own version for my project. I think some folks may get help out of your code anyway :)
